### ISSUE TITLE
Module not found: Error: Can't resolve '../package.json' in '/home/circleci/repo/node_modules/react-native-purchasely/lib/module'

### ISSUE THREAD

**Issue by keabard** [Purchasely/Purchasely-ReactNative#21]
Hello,

I'm building my Storybook with webpack on my CI, and since a recent version of the `react-native-purchasely` SDK, I get this error.

```
ERR! => Failed to build the preview
ERR! Module not found: Error: Can't resolve '../package.json' in '/home/circleci/repo/node_modules/react-native-purchasely/lib/module'
ERR! ModuleNotFoundError: Module not found: Error: Can't resolve '../package.json' in '/home/circleci/repo/node_modules/react-native-purchasely/lib/module'
ERR!     at /home/circleci/repo/node_modules/webpack/lib/Compilation.js:925:10
ERR!     at /home/circleci/repo/node_modules/webpack/lib/NormalModuleFactory.js:401:22
ERR!     at /home/circleci/repo/node_modules/webpack/lib/NormalModuleFactory.js:130:21
ERR!     at /home/circleci/repo/node_modules/webpack/lib/NormalModuleFactory.js:224:22
ERR!     at /home/circleci/repo/node_modules/neo-async/async.js:2830:7
ERR!     at /home/circleci/repo/node_modules/neo-async/async.js:6877:13
ERR!     at /home/circleci/repo/node_modules/webpack/lib/NormalModuleFactory.js:214:25
ERR!     at /home/circleci/repo/node_modules/enhanced-resolve/lib/Resolver.js:213:14
ERR!     at /home/circleci/repo/node_modules/enhanced-resolve/lib/Resolver.js:285:5
ERR!     at eval (eval at create (/home/circleci/repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
ERR!     at /home/circleci/repo/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
ERR!     at /home/circleci/repo/node_modules/enhanced-resolve/lib/Resolver.js:285:5
ERR!     at eval (eval at create (/home/circleci/repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
ERR!     at /home/circleci/repo/node_modules/enhanced-resolve/lib/Resolver.js:285:5
ERR!     at eval (eval at create (/home/circleci/repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
ERR!     at /home/circleci/repo/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
```
 
It happens when webpack builds a component that tries to import the `react-native-purchasely` SDK.

My version of `react-native-purchasely` is `2.2.3`

Do you know how I can solve this problem ? Thank you

**Comment by kherembourg** [comment]
Thanks for reporting this, issue has been fixed with #24
