### ISSUE TITLE
Crash when calling presentSubscriptions on Android

### ISSUE THREAD

**Issue by tezqa** [Purchasely/Purchasely-ReactNative#37]
When calling `presentSubscriptions()` on Android, the app crashes.

```ts
import Purchasely from "react-native-purchasely";
Purchasely.presentSubscriptions();
```

**Tested with:**
react-native-purchasely 2.4.4
@purchasely/react-native-purchasely-google 2.4.4

**Crash log:**
```
Fatal Exception: java.lang.IllegalArgumentException: No view found for id 0x7f0a013c (com.myapp:id/fragmentContainer) for fragment PLYSubscriptionsFragment{d9d0f68} (7bf764ce-6007-4a95-8557-13d1efea288d id=0x7f0a013c tag=SubscriptionsFragment)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:513)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3138)
       at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
       at android.app.Activity.performStart(Activity.java:8231)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3853)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2317)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by kherembourg** [comment]
This issue has been fixed with version 2.5.0
Thanks for reporting it
